### ISSUE TITLE
Program doesn't run because "ImportError: cannot import name 'Interfaces' from 'web.interfaces'"

### ISSUE THREAD

**Issue by nickzerangue** [doge/soundcloud-like-archiver#1]
When trying to execute the main.py file, it tries to import something from interfaces.py, which is a blank file. The program is completely unusable without it.
![image](https://user-images.githubusercontent.com/41443853/129993038-93cefb28-9c79-4572-8255-fe45f1cd40c1.png)

**Comment by doge** [comment]
I have updated the repo
